#! /bin/bash
execRun() {
	local nil=""
	if [[ "$1" == "--nil" ]]; then
		nil="$1"
		shift
	fi
	$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose run $nil "$@"
	rc=$?
	if ((rc!=0)); then
		echo "Run failed with exit code $rc"
	fi
	return $rc
}

execCompile() {
	if (($#==4)) && [[ "$1" == "--target" ]]; then
		if [[ ! -d "$3" ]]; then
			echo "Not a directory: $3"
			return 1
		fi
	fi
	if (($#==4)); then
		$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose compile "$@"
	elif (($#>0)); then
	 	$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose compile --target com.characterforming.ribose.base.SimpleTarget "$@"
	else
	 	$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose compile
	fi
	rc=$?
	if ((rc!=0)); then
		echo "Compile failed with exit code $rc"
	fi
	return $rc
}

execDecompile() {
	$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose decompile "$@"
	rc=$?
	if (($#==0)); then
		rc=0
	fi
	if ((rc!=0)); then
		echo "Decompile failed with exit code $rc"
	fi
}

execMap() {
	$JAVA -ea -cp $path $vmargs com.characterforming.ribose.Ribose map "$@"
	rc=$?
	if (($#==0)); then
		rc=0
	fi
	if ((rc!=0)); then
		echo "Map failed with exit code $rc"
	fi
}

execHelp() {
	local selector="help"
	if (($#>0)); then
		selector=$1
	fi
	shift $#
	case $selector in
	compile) execCompile;;
	run) execRun;;
	decompile) execDecompile;;
	map) execMap;;
	*) echo "Usage: ribose help [compile | run | decompile | map]";
	esac
	return 0
}

JAVA=$(which java)
if [[ ! -f "$JAVA" ]]; then
	echo No java at "$JAVA"
	exit 1
fi
jrte=$(realpath $(dirname $0))
vmargs=""
while [[ ! "$1" =~ ^(help|compile|run|decompile|map) ]]; do
	vmargs="$vmargs $1";
	shift
	if (($#==0)); then
		execHelp
		exit 0
	fi
done
selector=$1
shift
jars=$jrte/jars
path="$jars/$(cat $jrte/version).jar"
if (($#>1)) && [[ "$1" == "--target-path" ]]; then
	if [[ ! -z "$2" ]]; then
		path="$path:$(realpath $2)"
		shift
	fi
	shift
fi

case $selector in
help) execHelp $@;;
compile) execCompile $@;;
run) execRun $@;;
decompile) execDecompile $@;;
map) execMap $@;;
*) execHelp $@;;
esac