#! /bin/bash
if (($#<4)); then
	echo " Usage: bench <iteration-count> <model-path> <transducer> <input-path>"
	exit 1
fi 
n=$1
model=$2
transducer=$3
input=$4
shift 4
output="-Djrte.out.enabled=false -Dregex.out.enabled=false"
cp="-cp jars/$(cat version).jar;jars/$(cat version)-test.jar"
for i in $(seq $n); do
	gc="-Xms2m"
	${JAVA_HOME}/bin/java $gc -Dfile.encoding=UTF-8 $output $cp com.characterforming.jrte.test.FileRunner --nil "$model" $transducer "$input" "$@"
done
