#! /bin/bash
if (($#<4)); then
	echo " Usage: bench <iteration-count> <model-path> <transducer> <input-path>"
	echo "Output: /tmp/bench.<transducer>.time, /tmp/bench-<transducer>-<iteration>.gc"
	exit 1
fi 
n=$1
model=$2
transducer=$3
input=$4
shift 4
output="-Djrte.out.enabled=true -Dregex.out.enabled=false"
cp="-classpath jars/$(cat version).jar"
rm -f /tmp/bench-*.{gc,out}
for i in $(seq $n); do
	echo -n "$transducer " >> /tmp/bench.$transducer.time
	gc="-Xms2m -Xlog:gc*:file=/tmp/bench-$transducer-$i.gc"
	${JAVA_HOME}/bin/java $output $cp $gc -Dfile.encoding=UTF-8 com.characterforming.ribose.TRun --nil "$model" $transducer "$input" "$@" \
	> /tmp/bench-$transducer-$i.out
done
