#! /bin/bash
jrte=$(realpath $(dirname $0)/../..)
jars=$jrte/jars
version=$(cat $jrte/version)
path="$jars/$version.jar"
if (($#>3)) && [[ "$1" == "--target-path" ]]; then
	tpath=$(realpath "$2")
	if [[ -e "$tpath" ]]; then
		path="$path:$tpath"
		shift 2
	fi
fi
if (($#==2)); then
	model="$1"
	transducer="$2"
	${JAVA_HOME}/bin/java -ea -cp "$path" com.characterforming.ribose.TDecompile "$model" "$transducer"
else 
	echo "Usage: decompile [--target-path <target-classpath>] <model-file-path> <transducer>"
	echo "Decompile ribose transducer from model in <model-file-path>."
	exit 1
fi	
