#!/bin/bash
#set -x
vmargs=""
while [[ "$1" =~ ^[-][^-] ]]; do
	vmargs="$vmargs $1";
	shift
done
nil=""
if [[ "$1" == "--nil" ]]; then
  nil="$1"
  shift
fi
if (($#<3)) || (($#>4)); then
	echo "Usage: FileRunner [<vm-arg> ...] [--nil] <model-path> <transducer> <infile-path> [<unquoted-regex>]"
	echo "Use (vm-args) '-Djrte.out.enabled=false' and/or '-Dregex.out.enabled=false' to mute output."
	echo "<unquoted-regex> tokens will be concatenated with space delimiters."
else
	model="$1"
	transducer="$2"
	input="$3"
	shift 3
	jars="$(dirname $(readlink -f $0))/../../jars"
	java="java -cp $jars/ribose-0.0.0.jar:$jars/ribose-0.0.0-test.jar"
	{ time $java $vmargs com.characterforming.jrte.test.FileRunner $nil "$model" "$transducer" "$input" $* ; } 2>/tmp/$transducer.tmpx
  last=$(ls -1t ribose-runtime*.log|head -n 1)
	mbps=$(grep -Eio "$transducer :[ ]*[0-9.]* mb/s;" $last|tail -n 1|grep -Eo " [0-9.]+ "|tr -d ' ')
	echo -e "$(cat /tmp/$transducer.tmpx | tr '\r\n\t' ' ' | tr -s ' ')${mbps} mb/s $transducer" >/tmp/$transducer.time
	cp /tmp/$transducer.time build/testenv
	rm /tmp/$transducer.tmpx
fi
