#!/bin/bash
#set -x
vmargs=""
while [[ "$1" =~ ^[-][^-] ]]; do
	vmargs="$vmargs $1";
	shift
done
nil=""
if [[ "$1" == "--nil" ]]; then
  nil="$1"
  shift
fi
if (($#<3)) || (($#>4)); then
	echo "Usage: FileRunner [<vm-arg> ...] [--nil] <model-path> <transducer> <infile-path> [<unquoted-regex>]"
	echo "Use (vm-args) '-Djrte.out.enabled=false' and/or '-Dregex.out.enabled=false' to mute output."
	echo "<unquoted-regex> tokens will be concatenated with space delimiters."
else
	model="$1"
	transducer="$2"
	input="$3"
	shift 3
	version="$(cat version)"
	jars="$(dirname $(readlink -f $0))/../../jars"
	java="java -cp $jars/$version.jar:$jars/$version-test.jar"
	$java $vmargs com.characterforming.jrte.test.FileRunner $nil "$model" "$transducer" "$input" $*
fi
