#! /bin/bash
if (($# <2)) || (($#>3)); then
	echo "Usage: patterns <ginr-source-directory> <prologue-file> [<epilogue-file>]"
	echo "Effect: 'cat <prologue-file> <ginr-source-file> [<epilogue-file>] | ginr' for each ginr source in <ginr-source-directory>"
	echo "Tracing info including ginr error messages for X.inr are written to /tmp/X.inr.ginrout"
	exit 1
fi
if [[ ! -d "$1" ]]; then 
	echo "Not a directory: $1"
	exit 1
fi
if [[ ! -f "$2" ]]; then 
	echo "Not found: $2"
	exit 1
fi
if (($#==3)) && [[ ! -f "$3" ]]; then 
	echo "Not found: $3"
	exit 1
fi
jrte=$(realpath $(dirname $0)/../..)
jars=$jrte/jars
version=$(cat $jrte/version)
path="$jars/$version.jar:$jars/$version-test.jar"

ginr="$jrte/etc/ginr/ginr"
if [[ "$OS" =~ ^Windows ]]; then
	ginr="$ginr.exe"
fi

failed=0
echo ":bye;" | $ginr | grep ' '
for f in "$1"/*.inr; do
	if [[ "$f" != "$prologue" && "$f" != "$epilogue" ]]; then
		file=$(basename "$f")
		name=${file%.inr}
		cat $2 $f $3 | $ginr &> "/tmp/$name.ginrout"
		grep --basic-regexp --before-context=2 --after-context=2 \
			'^[ ]*\* \* \*\|^[ ]*\*\*\*\|^Error detected at state [0-9]*:\|^Reserved character:\|^Warning:' \
			"/tmp/$name.ginrout" &> "/tmp/$name.ginrerr"
		if [[ -s "/tmp/$name.ginrerr" ]]; then
			((++failed))
			echo "Errors reported for $file in /tmp/$name.ginrout (summary in /tmp/$name.ginrerr)"
		else
			for dfa in $(grep '^[A-Z0-9a-z_]*[ ]*:.*save' "$f" | grep -o '^[A-Z0-9a-z_]*' | sort -u); do
				grep "$dfa .*DFA MIN" "/tmp/$name.ginrout"
			done
		fi
	fi
done

if ((failed>0)); then
	echo "$failed errors reported, see /tmp/*.ginrerr"
	find /tmp -name '*.ginrerr' -type f -not -empty -exec cat "{}" \; 2>/dev/null
	exit 1
else
	exit 0
fi
