#! /bin/bash
if (($# <2)) || (($#>3)); then
	echo "Usage: patterns <ginr-source-directory> <prologue-file> [<epilogue-file>]"
	echo "Effect: 'cat <prologue-file> <ginr-source-file> [<epilogue-file>] | ginr' for each ginr source in <ginr-source-directory>"
	echo "Tracing info including ginr error messages for X.inr are written to /tmp/X.inr.ginrout"
	exit 1
fi
if [[ ! -d "$1" ]]; then 
	echo "Not a directory: $1"
	exit 1
fi
if [[ ! -f "$2" ]]; then 
	echo "Prologue not found: $2"
	exit 1
fi
if (($#==3)) && [[ ! -f "$3" ]]; then 
	echo "Epilogue not found: $3"
	exit 1
fi

ginr=$(which ginr 2>/dev/null)
if [[ ! -x "$ginr" ]]; then
	ginr="etc/ginr/ginr"
	if [[ "$OS" =~ ^Windows ]]; then
		ginr="$ginr.exe"
	fi
	if [[ ! -x "$ginr" ]]; then
		echo "Could not find ginr executable in search path or in etc/ginr"
		exit 1
	fi
fi
echo ginr@$(realpath "$ginr")
echo ":bye;" | "$ginr" | grep ' '

failed=""
for f in "$1"/*.inr; do
	if [[ "$f" != "$prologue" && "$f" != "$epilogue" ]]; then
		file=$(basename "$f")
		name=${file%.inr}
		cat $2 $f $3 | "$ginr" &> "/tmp/$name.ginrout"
		grep -n --basic-regexp --before-context=2 --after-context=2 \
			'^[ ]*\* \* \*\|^[ ]*\*\*\*\|^Error detected at state [0-9]*:\|^Reserved character:\|^Warning:\|^Assertion failed' \
			"/tmp/$name.ginrout" &> "/tmp/$name.ginrerr"
		if [[ ! -s "/tmp/$name.ginrerr" ]]; then
			for dfa in $(grep '^[A-Z0-9a-z_]*[ ]*:.*save' "$f" | grep -o '^[A-Z0-9a-z_]*'); do
				grep "$dfa .*DFA MIN" "/tmp/$name.ginrout"
			done
		else
			failed="$failed $name"
		fi
	fi
done

if [[ ! -z "$failed" ]]; then
	for name in $failed; do
		echo "Errors reported in /tmp/$name.ginrout:"
		cat /tmp/$name.ginrerr
	done
	exit 1
fi

exit 0
