#! /bin/bash
clean=0
if [[ "$1" == "--clean" ]]; then
  clean=1
  shift
fi
short=0
if [[ "$1" == "--short" ]]; then
  short=1
  shift 1
fi

c="$(git log --oneline -n 1|grep -Eo '^[0-9a-f]+')"
if [[ ! -z $(git ls-files etc/sh/regress) ]]; then
  g="$(git log --oneline -n 1 etc/sh/regress|grep -Eo '^[0-9a-f]+')"
else
  g="fffffff";
fi
for f in $(ls -1tr "$@"); do
  grep 'gc,heap' $f | grep -o '\] .*$' | grep -o ' .*$' | grep -o '[^ ].*$' | tr -s ' ' > $f.stats
  if ((clean==1)); then
    echo -e "\n---$f" >> regression.gc
    cat $f.stats >> regression.gc
  fi
done