#! /bin/bash
#set -x
vmargs=""
while [[ "$1" =~ ^[-][^-] ]]; do
	vmargs="$vmargs $1";
	shift
done
nil=""
if [[ "$1" == "--nil" ]]; then
  nil="$1"
  shift
fi
if (($#!=3 && $# != 4)); then
	echo "Usage: ribose [<vm-arg> ...] [--nil] <model-file> <transducer> <input-file>|'-' [<output-file>]"
 	echo "Use (vm-args) '-Djrte.out.enabled=false' and/or '-Dregex.out.enabled=false' to mute output."
  echo "Use '-' for input-path to read from System.in; default output stream is System.out."
else
  version=$(cat version)
  jars="$(dirname $(readlink -f $0))/../../jars"
  java="${JAVA_HOME}/bin/java -cp $jars/$version.jar:$jars/$version-test.jar $vmargs com.characterforming.ribose.TRun"
	model="$1"
	transducer="$2"
	input="$3"
  if (($#>3)); then
    $java $nil "$model" "$transducer" "$input" "$4"
  else
    $java $nil "$model" "$transducer" "$input"
  fi
fi
#set +x